### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by RolfKoenders** [lucamaraschi/sheridan#1] opened 2015-10-20 05:54 UTC
The name of the repo doesn't make any sense.. It's not nice name for a project... 

😂😂

**Comment by lucamaraschi** [comment] 2015-10-20 06:09
Sheridan is a mythological figure, half human and half animal with the peculiar features of being born without brain , eunuch and with a triangular face. The legend tells that few of these were seen in the rural area near [Corby](https://en.wikipedia.org/wiki/Corby).
The name reflects the intent of this library, being simple, geometrically sharp and solid connection pool manager for Postgres SQL.

**Comment by RolfKoenders** [comment] 2015-10-20 06:13
Being simple? Hahaha :+1:

**Comment by lucamaraschi** [comment] 2015-10-20 12:09
I am closing this issue has it's a know issue by design

**Closed as completed by lucamaraschi** 2015-10-20 12:09 UTC

**Comment by RolfKoenders** [comment] 2015-10-20 12:12
This guy has issues... :warning:
